build:
  image: docker:dind
  privileged: true
  commands:
    - sed -i -- 's/latest/$$PHP_VERSION/g' Dockerfile
    - docker info
    - docker build -t continuousdeployment/php:$$PHP_VERSION .
matrix:
  PHP_VERSION:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - latest
