build:
  image: docker:dind
  privileged: true
  commands:
    - docker --version
    - sed -i -- 's/latest/$$PHP_VERSION/g' Dockerfile
    - echo $$PHP_VERSION
    - cat Dockerfile
matrix:
  PHP_VERSION:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - latest
