compose:
  dind:
    image: docker:dind
    privileged: true
    commands:
      - docker --version
      - echo $$PHP_VERSION
matrix:
  PHP_VERSION:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - latest
